@api = http://localhost:3000/api/todos
@libraryId = 65a8a1830d7aa23921cd7035
@bookId = 65a8a18d0d7aa23921cd7036


### Get all todos
GET {{api}}/

### Get one todos
GET {{api}}/1


### Create a new todo
POST {{api}}/
Content-Type: application/json

{
  "title": "go to the store",
  "progress": 40,
  "description": "go to the store"
}


### Update a todo
PUT  {{api}}/1
Content-Type: application/json

{
  "progress": 60
}
