@api = http://localhost:3000
@libraryId = 65a8a1830d7aa23921cd7035
@bookId = 65a8a18d0d7aa23921cd7036


### check health
GET {{api}}/health


### Return all libraries
GET {{api}}/library


### Create a new library
POST {{api}}/library
Content-Type: application/json

{
    "name": "test library 3",
    "address": "some adress"
}

### Get a library
GET {{api}}/library/{{libraryId}}


### Delete a library
DELETE {{api}}/library/{{libraryId}}



### Create a new book
POST {{api}}/library/{{libraryId}}/books
Content-Type: application/json

{
    "title": "test book 4",
    "author": "me",
    "year": "2022"
}


### Get all books of library
GET {{api}}/library/{{libraryId}}/books


### Get one book of library
GET {{api}}/library/{{libraryId}}/books/{{bookId}}


### ### Delete a book of library
DELETE {{api}}/library/{{libraryId}}/books/{{bookId}}