@api = http://localhost:3000/api/v1/blog
@id = 2

### Get all blogs
GET {{api}}

### Get one blog
GET {{api}}/{{id}}


### Create a new blog
POST {{api}}
Content-Type: application/json

{
  "name": "name 3",
  "author": "Stivenson",
  "reads": 20
}


### Update a blog
PUT {{api}}/{{id}}
Content-Type: application/json

{
  "name": "name 2",
  "author": "loo",
  "reads": 10
}


### Delete a blog
DELETE {{api}}/{{id}}